%YAML 1.2
---

name:           Senior Badger (Badger II)
description:    You got 50 or more Fedora Badges
creator:        ralph
discussion:     https://fedorahosted.org/fedora-badges/ticket/12
image_url:      https://badges.fedoraproject.org/pngs/badger-02.png
issuer_id:      fedora-project

trigger:
  topic:  fedbadges.badge.award

criteria:
  datanommer:
      filter:
        topics:
        - "%(topic)s"
        users:
        - "%(msg.user.username)s"
      operation: count
      condition:
        greater than or equal to: 50

recipient: "%(msg.user.username)s"
