%YAML 1.2
---

name:           Junior Badger (Badger I)
description:    You got your first 10 Fedora Badges
creator:        ralph
discussion:     https://fedorahosted.org/fedora-badges/ticket/11
image_url:      https://badges.fedoraproject.org/pngs/badger-01.png
issuer_id:      fedora-project

trigger:
  topic:  fedbadges.badge.award

criteria:
  datanommer:
      filter:
        topics:
        - "%(topic)s"
        users:
        - "%(msg.user.username)s"
      operation: count
      condition:
        greater than or equal to: 10

recipient: "%(msg.user.username)s"
