%YAML 1.2
---

# This is some metadata about the badge
name:           Badge Muse (Badge Ideas I)
description:    You proposed a new idea for a Fedora Badge.  Thanks!
creator:        ralph

# This is a link to the discussion about adopting this as a for-real badge.
discussion:     https://fedorahosted.org/fedora-badges/ticket/2

# A link to the image for the badge
image_url:      http://infrastructure.fedoraproject.org/infra/badges/pngs/badge-muse-01.png

# That's us!
issuer_id:      fedora-project

# We'll perform our more costly check (defined below) only when
# we receive messages that match this 'trigger'
trigger:
  all:
  - topic: trac.ticket.new
  - lambda:  not msg.get('msg', {}).get('instance', {}).get('project_name', None) == 'fedora-badges'

# Once the check has been triggered, this defines what we actually check.
criteria:
  datanommer:
      filter:
        topics:
        - "%(topic)s"
        users:
        - "%(msg.agent)s"
      operation: count
      condition:
        greater than or equal to: 1

recipient_key: "%(msg.agent)s"
