%YAML 1.2
---

# This is some metadata about the badge
name:           Take this and call me in the morning
description:    You submitted an update to bodhi with one or more bugzilla bug numbers attached
creator:        ralph
discussion:     https://fedorahosted.org/fedora-badges/ticket/235
image_url:      https://badges.fedoraproject.org/pngs/take-this.png
issuer_id:      fedora-project

# If we receive any bodhi message for which there is more than one build, then
# award the badge to the submitter of that update.
trigger:
  all:
  - any:
    - topic:  bodhi.update.request.stable
    - topic:  bodhi.update.request.testing
  - lambda: "len(msg.get('msg', {}).get('update', {}).get('bugs', [])) > 0"

# This criteria check could just be left empty since the trigger matching is all
# that we need.  We'll do something trivial just because fedbadges demands a
# criteria block.  We can remove this in the future.
criteria:
  datanommer:
      filter:
        topics:
        - "%(topic)s"     # The topic of the message that triggered us.
        users:
        - "%(msg.update.submitter)s"  # The user that was created.
      operation: count
      condition:
        greater than or equal to: 1 

recipient: "%(msg.update.submitter)s"
