%YAML 1.2
---

# This is some metadata about the badge
name:           Corporate Drone
description:    You submitted an Bodhi update for an EPEL branch.
creator:        ralph
discussion:     https://fedorahosted.org/fedora-badges/ticket/220
image_url:      https://badges.fedoraproject.org/pngs/corporate-drone.png
issuer_id:      fedora-project

# We'll perform our more costly check (defined below) only when
# we receive messages that match this 'trigger'
trigger:
    all:
    - topic:  bodhi.update.request.testing
    - lambda: msg.get('msg', {}).get('update', {}).get('release', {}).get('id_prefix', None) == 'FEDORA-EPEL'

# Once the check has been triggered, this defines what we actually check.
criteria:
  datanommer:
      filter:
        topics:
        - "%(topic)s"     # The topic of the message that triggered us.
        users:
        - "%(msg.update.submitter)s"  # The user that was created.
      operation: count
      condition:
        greater than or equal to: 1 

recipient: "%(msg.update.submitter)s"
