%YAML 1.2
---

name:           Ambassador
description:    You were sponsored as an Ambassador, a representative of Fedora.
creator:        ralph
discussion:     https://fedorahosted.org/fedora-badges/ticket/28
image_url:      https://badges.fedoraproject.org/pngs/fas-ambassador.png
issuer_id:      fedora-project

trigger:
  all:
  - topic:  fas.group.member.sponsor
  - lambda: msg.get('msg', {}).get('group', None) == 'ambassadors'

criteria:
  datanommer:
      filter:
        topics:
        - "%(topic)s"
        users:
        - "%(msg.user)s"
      operation: count
      condition:
        greater than or equal to: 1

recipient: "%(msg.user)s"
