%YAML 1.2
---

name:           FEL Member
description:    You hack on the Fedora Electronic Lab
creator:        ralph
discussion:     https://fedorahosted.org/fedora-badges/ticket/137
image_url:      https://badges.fedoraproject.org/pngs/FEL_member.png
issuer_id:      fedora-project

trigger:
  all:
  - topic:  fas.group.member.sponsor
  - lambda: msg.get('msg', {}).get('group', None) == 'git-fedora-electronic-lab'

criteria:
  datanommer:
      filter:
        topics:
        - "%(topic)s"
        users:
        - "%(msg.user)s"
      operation: count
      condition:
        greater than or equal to: 1

recipient: "%(msg.user)s"
