%YAML 1.2
---

name:           Pixel Ninja
description:    Now a proud member of the Fedora Design Team
creator:        ralph
discussion:     https://fedorahosted.org/fedora-badges/ticket/89
image_url:      https://badges.fedoraproject.org/pngs/design-team.png
issuer_id:      fedora-project

trigger:
  all:
  - topic:  fas.group.member.sponsor
  - lambda: msg.get('msg', {}).get('group', None) == 'designteam'

criteria:
  datanommer:
      filter:
        topics:
        - "%(topic)s"
        users:
        - "%(msg.user)s"
      operation: count
      condition:
        greater than or equal to: 1

recipient: "%(msg.user)s"
