%YAML 1.2
---

name:           White Rabbit
description:    Indicated your timezone in FAS so everyone can sync with you
creator:        ralph

discussion:     https://fedorahosted.org/fedora-badges/ticket/52
image_url:      https://badges.fedoraproject.org/pngs/fas-white-rabbit.png
issuer_id:      fedora-project

trigger:
  all:
  - topic: fas.user.update
  - lambda: "'timezone' in msg.get('msg', {}).get('fields', [])"

# Once the check has been triggered, this defines what we
# actually check.
criteria:       
  datanommer:
      filter:
        topics:
        - "%(topic)s"
      operation: count
      condition:
        greater than or equal to: 1

recipient: "%(msg.user)s"
