%YAML 1.2
---

name:           Paranoid Panda
description:    You updated your password with the Fedora Account System (FAS)
creator:        lmacken

# This is a link to the discussion about adopting this as a for-real badge
discussion:     https://fedorahosted.org/fedora-badges/ticket/57

# A link to the image for the badge.
image_url:      https://badges.fedoraproject.org/pngs/fas-paranoid-panda.png

# The issuer.
issuer_id: fedora-project

trigger:
  all:
  - topic: fas.user.update
  - lambda: "'password' in msg.get('msg', {}).get('fields', [])"

# Once the check has been triggered, this defines what we
# actually check.
criteria:       
  datanommer:
      filter:
        topics:
        - "%(topic)s"
      operation: count
      condition:
        greater than or equal to: 1

recipient: "%(msg.user)s"
