%YAML 1.2
---

name:           Videographer
description:    You are a member of the videos team
creator:        ralph
discussion:     https://fedorahosted.org/fedora-badges/ticket/171
image_url:      https://badges.fedoraproject.org/pngs/videographer.png
issuer_id:      fedora-project

trigger:
  all:
  - topic:  fas.group.member.sponsor
  - lambda: msg.get('msg', {}).get('group', None) == 'videos'

criteria:
  datanommer:
      filter:
        topics:
        - "%(topic)s"
        users:
        - "%(msg.user)s"
      operation: count
      condition:
        greater than or equal to: 1

recipient: "%(msg.user)s"
