%YAML 1.2
---

# This is some metadata about the badge
name:           Free the Fedora II
description:    You helped to spread Fedora by handling 10 Free Media tickets.
creator:        ralph
discussion:     https://fedorahosted.org/fedora-badges/ticket/98
image_url:      https://badges.fedoraproject.org/pngs/free-mediaII.png
issuer_id:      fedora-project

# We'll perform our more costly check (defined below) only when
# we receive messages that match this 'trigger'
trigger:
  all:
  - topic: trac.ticket.update
  - lambda:  msg.get('msg', {}).get('instance', {}).get('project_name', None) == 'Fedora Freemedia'
  - lambda:  "'status' in msg.get('msg', {}).get('old_values', {})"
  - lambda:  msg.get('msg', {}).get('ticket', {}).get('status', None) == 'closed'
  - lambda:  msg.get('msg', {}).get('ticket', {}).get('resolution', None) == 'fixed'

# Once the check has been triggered, this defines what we actually check.
criteria:
  datanommer:
      filter:
        topics:
        - "%(topic)s"
        users:
        - "%(msg.agent)s"
        rows_per_page: 9999999
      operation:
        lambda: len([msg for msg in query.all() if msg.msg['instance']['project_name'] == 'Fedora Freemedia' and msg.msg['ticket']['status'] == 'closed' and msg.msg['ticket']['resolution'] == 'fixed'])
      condition:
        greater than or equal to: 10

recipient: "%(msg.agent)s"
