%YAML 1.2
---

name:           Sensei
description:    You ran a class in the Fedora Classroom!
creator:        ralph
discussion:     https://fedorahosted.org/fedora-badges/ticket/119
image_url:      https://badges.fedoraproject.org/pngs/sensei.png
issuer_id:      fedora-project

# They must hold a meeting in #fedora-classroom attended by themselves, zodbot,
# and at least one other person.
trigger:
  all:
  - topic: meetbot.meeting.complete
  - lambda: "'#fedora-classroom' == msg.get('msg', {}).get('channel', None)"
  - lambda: "len(msg.get('msg', {}).get('attendees', {})) > 2"

# Once the check has been triggered, this defines what we actually check.
criteria:
  datanommer:
      filter:
        topics:
        - "%(topic)s"     # The topic of the message that triggered us.
      operation: count
      condition:
        greater than or equal to: 1

recipient: "%(msg.chairs)s"
recipient_nick2fas: Yes
