%YAML 1.2
---

# This is some metadata about the badge
name:           Secretary General
description:    Chaired an IRC meeting.
creator:        ralph

# This is a link to the discussion about adopting this as a for-real badge.
discussion:     https://github.com/oddshocks/badges/blob/master/docs/badges.rst

# A link to the image for the badge
image_url:      http://infrastructure.fedoraproject.org/infra/badges/pngs/irc-secretary-general.png

# That's us!
issuer_id: fedora-project

# We'll perform our more costly check (defined below) only when
# we receive messages that match this 'trigger'
trigger:
  topic: meetbot.meeting.complete

# Once the check has been triggered, this defines what we actually check.
criteria:
  datanommer:
      filter:
        topics:
        - "%(topic)s"     # The topic of the message that triggered us.
      operation: count
      condition:
        greater than or equal to: 1 

recipient: "%(msg.chairs)s"
