%YAML 1.2
---

name:           Civic Duty
description:    You participated in a Fedora town hall event
creator:        ralph
discussion:     https://fedorahosted.org/fedora-badges/ticket/200
image_url:      https://badges.fedoraproject.org/pngs/town-hall-participant.png
issuer_id:      fedora-project

trigger:
  all:
  - topic: meetbot.meeting.complete
  - lambda: "'#fedora-townhall-public' == msg.get('msg', {}).get('channel', None)"
  - lambda: "len(msg.get('msg', {}).get('attendees', {})) > 2"

# Once the check has been triggered, this defines what we actually check.
criteria:
  datanommer:
      filter:
        topics:
        - "%(topic)s"     # The topic of the message that triggered us.
      operation: count
      condition:
        greater than or equal to: 1

recipient: "%(msg.attendees)s"
recipient_nick2fas: Yes
