%YAML 1.2
---

# This is some metadata about the badge
name:           Mic Check! (Updates-Testing V)
description:    Pushed 1000 bodhi updates to the testing repositories.
creator:        ralph

# This is a link to the discussion about adopting this as a for-real badge.
discussion:     https://github.com/oddshocks/badges/pull/3

# A link to the image for the badge
image_url:      http://infrastructure.fedoraproject.org/infra/badges/pngs/is-this-thing-on-05.png
# That's us!
issuer_id: fedora-project

# We'll perform our more costly check (defined below) only when
# we receive messages that match this 'trigger'
trigger:
  topic:  bodhi.update.request.testing

# Once the check has been triggered, this defines what we actually check.
criteria:
  datanommer:
      filter:
        topics:
        - "%(topic)s"     # The topic of the message that triggered us.
        users:
        - "%(msg.update.submitter)s"  # The user that was created.
      operation: count
      condition:
        greater than or equal to: 1000

recipient: "%(msg.update.submitter)s"
