%YAML 1.2
---

# This is some metadata about the badge.
name:           Hatchling
description:    You added a new package to the distribution. Isn't it a cute lil' thing?
creator:        adamwill

# This is a link to the discussion about adopting this as a for-real badge.
discussion:     https://fedorahosted.org/fedora-badges/ticket/22

# A link to the image for the badge.
image_url:      https://badges.fedoraproject.org/pngs/pkgdb-hatchling-i.png

# The issuer.
issuer_id:      fedora-project

# We'll perform our more costly check (defined below)
# only when we receive messages that match this trigger.
trigger:
  topic:        pkgdb.package.new

# Once the check has been triggered, this defines what we
# actually check.
criteria:       
  datanommer:
      filter:
        topics:
        - "%(topic)s"     # The topic of the message that triggered us.
        users:
        - "%(msg.package_listing.point_of_contact)s"  # The owner of the newly created package.
      operation: count
      condition:
        greater than or equal to: 1 

recipient: "%(msg.package_listing.point_of_contact)s"
