%YAML 1.2
---

# This is some metadata about the badge
name:           Blag Dragster (Planet VII)
description:    You posted 160 or more things to the Fedora Planet!
creator:        ralph
discussion:     https://fedorahosted.org/fedora-badges/ticket/305
image_url:      https://badges.fedoraproject.org/pngs/planet-bloggin-it-07.png
issuer_id:      fedora-project

# We'll perform our more costly check (defined below) only when
# we receive messages that match this 'trigger'
trigger:
  topic: planet.post.new

# Once the check has been triggered, this defines what we actually check.
criteria:
  datanommer:
      filter:
        topics:
        - "%(topic)s"     # The topic of the message that triggered us.
        users:
        - "%(msg.username)s"
      operation: count
      condition:
        greater than or equal to: 160
