%YAML 1.2
---

# This is some metadata about the badge
name:           Blog Lobber (Planet VI)
description:    You posted 80 or more things to the Fedora Planet!
creator:        ralph

# This is a link to the discussion about adopting this as a for-real badge.
discussion:     https://fedorahosted.org/fedora-badges/ticket/295

# A link to the image for the badge
image_url:      https://badges.fedoraproject.org/pngs/planet-bloggin-it-06.png
# That's us!
issuer_id:      fedora-project

# We'll perform our more costly check (defined below) only when
# we receive messages that match this 'trigger'
trigger:
  topic: planet.post.new

# Once the check has been triggered, this defines what we actually check.
criteria:
  datanommer:
      filter:
        topics:
        - "%(topic)s"     # The topic of the message that triggered us.
        users:
        - "%(msg.username)s"
      operation: count
      condition:
        greater than or equal to: 80
