%YAML 1.2
---

# This is some metadata about the badge
name:           Riding the Bull Home (Tester VI)
description:    >
    *(great joy)*

    Tested and added karma to 80 updates-testing updates in Bodhi.

creator:        ralph

# This is a link to the discussion about adopting this as a for-real badge.
discussion:     https://github.com/oddshocks/badges/pull/8

# A link to the image for the badge
image_url:	http://infrastructure.fedoraproject.org/infra/badges/pngs/tester-06.png
# That's us!
issuer_id:      fedora-project

# We'll perform our more costly check (defined below) only when
# we receive messages that match this 'trigger'
trigger:
  all:
  - topic:  bodhi.update.comment
  - lambda:  not msg.get('msg', {}).get('comment', {}).get('anonymous', True)

# Once the check has been triggered, this defines what we actually check.
criteria:
  datanommer:
      filter:
        topics:
        - "%(topic)s"     # The topic of the message that triggered us.
        users:
        - "%(msg.comment.author)s"
      operation: count
      condition:
        greater than or equal to: 80 

recipient: "%(msg.comment.author)s"
