%YAML 1.2
---

name:           It still works!
description:    Tested an update for an older stable release of Fedora
creator:        ralph
discussion:     https://fedorahosted.org/fedora-badges/ticket/71
image_url:      https://badges.fedoraproject.org/pngs/it-still-works.png
issuer_id:      fedora-project

# TODO -- we have to update the .fc19 at the end of this string with .fc20 once f21 is GA
# http://infrastructure.fedoraproject.org/infra/docs/fedora-releases.txt
trigger:
  all:
  - topic:  bodhi.update.comment
  - lambda:  msg.get('msg', {}).get('comment', {}).get('update_title', 'nope').endswith('.fc19')

criteria:
  datanommer:
      filter:
        topics:
        - "%(topic)s"
        users:
        - "%(msg.comment.author)s"
      operation: count
      condition:
        greater than or equal to: 1

recipient: "%(msg.comment.author)s"
