%YAML 1.2
---

name:           Vacation
description:    Sip the lemonade away (You deserve it for remembering your responsibility)!
creator:        ralph
discussion:     https://fedorahosted.org/fedora-badges/ticket/245
image_url:      https://badges.fedoraproject.org/pngs/beach-bum.png
issuer_id:      fedora-project

trigger:
  all:
  - any:
    - topic:  fedocal.meeting.new
    - topic:  fedocal.meeting.update
  - any:
    - lambda: "msg.get('msg', {}).get('meeting', {}).get('calendar_name', '').startswith('vacation')"

criteria:
  datanommer:
      filter:
        topics:
        - "%(topic)s"     # The topic of the message that triggered us.
        users:
        - "%(msg.agent)s"
      operation: count
      condition:
        greater than or equal to: 1

recipient: "%(msg.agent)s"
