%YAML 1.2
---

name:           Let Me Introduce Myself
description:    Created your own user profile page on the Fedora Wiki
creator:        ralph

discussion:     https://fedorahosted.org/fedora-badges/ticket/41
image_url:      https://badges.fedoraproject.org/pngs/wiki-let-me-introduce-myself.png
issuer_id:      fedora-project

# If their name is Foo and they edited a page called User:Foo, then...
trigger:
  all:
  - topic: wiki.article.edit
  - lamba: msg.get('msg', {}).get('title', None) == "User:" + msg.get('msg', {}).get('user', None)

criteria:
  datanommer:
      filter:
        topics:
        - "%(topic)s"     # The topic of the message that triggered us.
        users:
        - "%(msg.user)s"
      operation: count
      condition:
        greater than or equal to: 1
