%YAML 1.2
---

# This is some metadata about the badge
name:           You can call me "Patches" (SCM IV)
description:    Pushed 400 commits to a Fedora package repository.
creator:        ralph

# This is a link to the discussion about adopting this as a for-real badge.
discussion:     https://github.com/oddshocks/badges/blob/master/docs/badges.rst

# A link to the image for the badge
image_url:	http://infrastructure.fedoraproject.org/infra/badges/pngs/you-can-call-me-patches-04.png
# That's us!
issuer_id: fedora-project

# We'll perform our more costly check (defined below) only when
# we receive messages that match this 'trigger'
trigger:
  topic:  git.receive

# Once the check has been triggered, this defines what we actually check.
criteria:
  datanommer:
      filter:
        topics:
        - "%(topic)s"     # The topic of the message that triggered us.
        users:
        - "%(msg.commit.username)s"
      operation: count
      condition:
        greater than or equal to: 400 
